services:
  pocket-clone:
    image: ghcr.io/potto007/pocket-clone:latest
    container_name: pocket-clone
    ports:
      - "8080:8080"
    volumes:
      - pocket-data:/data
    restart: unless-stopped

volumes:
  pocket-data:
